config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

	scope module: 'clans' do
	  resources :clans do
	    resources :clan_messages, shallow: true
			resources :clan_members, shallow: true
			resources :clan_messages, shallow: true
			resources :clan_ranks, shallow: true
			resources :clan_events, only: [:index]
			resources :clan_links, only: [:index]
			resources :clan_contacts, only: [:create]
			resources :clan_applications, only: [:index, :destroy, :create, :show] do
				patch 'accept' => 'clan_applications#accept', as: :accept, on: :member
			end
			resources :clan_donations, only: [:create] do
				post 'ipn_notification' => 'clan_donations#ipn_notification', on: :member
				get  'thanks' => 'clan_donations#thanks', on: :member
			end
			patch 'change_owner' => 'clans#change_owner', on: :member
			patch 'unblock_member/:clan_member_id' => 'clans#unblock_member', on: :member
			patch 'clan_members/:clan_member_id' => 'clans#clan_members_update', on: :member
			delete 'remove_member/:clan_member_id' => 'clans#remove_member', on: :member
	  end
	  resources :clan_invites
	  post 'clan_invites/:clan_invite_id/accept' => 'clan_invites#accept', as: 'accept_clan_invite'
	end

  get 'clan_notices/:clan_id/new' => 'clans/clan_notices#new', as: 'new_clan_notice'
  get 'clan_notices/:id' => 'clans/clan_notices#show', as: 'clan_notice'
  post 'clan_notices/:clan_id/new' => 'clans/clan_notices#create'
  delete 'clan_notices/:id' => 'clans/clan_notices#destroy', as: 'delete_clan_notice'

  get 'system_notices/new' => 'system_notices#new', as: 'new_system_notice'
  get 'system_notices/:id' => 'system_notices#show', as: 'system_notice'
  get 'system_notices' => 'system_notices#index', as: 'system_notices'
  post 'system_notices/new' => 'system_notices#create'
  delete 'system_notices/:id' => 'system_notices#destroy', as: 'delete_system_notice'

	resources :announcements, only: :index
	post 'announcements/read' => 'announcements#read'

	devise_for :admins, controllers: { sessions: 'admin/sessions' }
	devise_for :users,  controllers: { sessions: 'user/sessions', registrations: 'user/registrations', confirmations: 'user/confirmations' }

	authenticate :admin do
		mount Sidekiq::Web => '/sidekiq'
  end

	authenticated :admin do
		root to: 'admin/dashboard#index', as: :authenticated_admin
		namespace :admin do
			resources :games
			resources :game_systems
			resources :charities
			resources :cancellations
		  resources :users
			resources :rosters
			resources :reports
			resources :events, only: :index
			get 'cancellations/(:rosters)' => 'cancellations#index'
			patch 'cancellations/:id/uncancel' => 'cancellations#uncancel'
			post 'users/:id/become/(:prev_action)' => 'users#become', as: 'user_become'
			get 'users/:id/confirm' => 'users#confirm', as: 'user_confirm'
			get 'users/:id/account'  => 'users#account', as: 'user_account'
		end
	end

	authenticated :user do
		root to: 'dashboard#index', as: :authenticated_user
	end

	unauthenticated do
		devise_scope :user do
			root to: 'pages#home', as: :unauthenticated_user
			get 'tosmodal' => 'user/registrations#tosmodal', as: 'tosmodal'
		end
	end

	#the following resources are actually all the same model - the user.
	#it just made breaking up the CRUD for the user easier because we're using
	#inherited resources.
	resource :user, path: 'profile', controller: 'profile/profile', as: 'profile'
	namespace :profile do
		resource :user, path: 'country', controller: 'country', as: 'country', only: [ :edit, :update ]
		resource :user, path: 'account', controller: 'account', as: 'account'
		resource :user, path: 'games', controller: 'games_and_systems', as: 'games_and_systems'
		resources :blocks
		resources :favorites
                resource :notifications, only: [:edit, :update]
		get 'avatar' => 'avatar#index'
		get 'subscription' => 'subscription#index'
                post 'add-game-modal' => 'games_and_systems#add_game', as: 'add_game'
                get 'check-user-system' => 'games_and_systems#check_game', as: 'check_game'
	end

	#the following both deal with the contracts controller - my-contracts is
	#obviously just scoped to the current user.
	get 'contracts/close_pay_pal' => 'contracts/contracts#close_pay_pal'

	resources :contracts, controller: 'contracts/contracts', path: 'looking-for-players'

	resources :contracts, controller: 'players/players', path: 'players', as: 'players'

	resources :contracts, controller: 'contracts/contracts', only: [] do
		#we're going to break the REST model as paypal doesn't allow sending
		#post/patch method via the return url.  We'll have to confirm the payment
		#from paypal via IPN anyways, but the following purchase method will
		#just set the status of contract to pending payment
		get 'purchase' => 'contracts/contracts#purchase'

		#IPN url
		post 'ipn_notification' => 'contracts/contracts#ipn_notification'

		post  'payment_request' => 'contracts/contracts#payment_request', as: 'payment_request'

		post 'claim' => 'contracts/contracts#claim'

	end

	namespace :subscriptions do
		get 'abort'
		get 'cancel'
		get 'ipn_notification'
	end

	resources :subscription_plans, only: [] do
    	resources :subscriptions, shallow: true
  	end

	get 'multiple_times' => 'contracts/posted_contracts#multiple_times_new', as: 'multiple_times_new'
	post 'multiple_times' => 'contracts/posted_contracts#multiple_times_create', as: 'multiple_times_create'

	resources :contracts, path: 'my-posted-events', controller: 'contracts/posted_contracts', as: 'posted_contracts' do
		get 'cancel' => 'contracts/posted_contracts#cancel', as: 'cancel'
		patch 'rate' => 'contracts/posted_contracts#rate', as: 'rate'
		patch 'claim' => 'contracts/posted_contracts#claim', as: 'claim'
		patch 'deny' => 'contracts/posted_contracts#deny', as: 'deny'
	end

	resources :contracts, path: 'my-claimed-events', controller: 'contracts/claimed_contracts', as: 'claimed_contracts' do
		get 'cancel' => 'contracts/claimed_contracts#cancel', as: 'cancel'
		patch 'rate' => 'contracts/claimed_contracts#rate', as: 'rate'
	end

	resources :rosters do
		get 'cancel', as: 'cancel', on: :member
		get 'add_invitees' => 'rosters#add_invitees', on: :member
    	resources :roster_messages, shallow: true
    	resources :invites, only: [ :create ]
	end

	resources :roster_invites, only: [:create]

	resources :invites, only: [:destroy] do
		patch 'claim', on: :member
		patch 'decline', on: :member
		patch 'waitlist', on: :member
		patch 'no_show', on: :member
		patch 'reconfirm', on: :member
		put  :update_position, on: :member
	end

	resources :events, path: 'my-events', only: :index
	resource :events do
		get 'view_all' => 'events#view_all'
	end
	resources :events, only: :show

	get 'add_invitees' => 'rosters#add_invitees', as: 'add_invitees'
	post 'add_invitees_create' => 'invites#add_invitees_create', as: 'add_invitees_create'

	get 'add_game_modal' => 'dashboard#add_game_modal'

	#the following both deal with the bounties controller - my-bounties is
	#obviously just scoped to the current user.
	get 'bounties/close_pay_pal' => 'bounties/bounties#close_pay_pal'
	get 'bounties/feed' => 'bounties/bounties#feed'

	resources :bounties, controller: 'bounties/bounties', path: 'public-games'

	resources :bounties, controller: 'bounties/bounties', only: []  do
		#we're going to break the REST model as paypal doesn't allow sending
		#post/patch method via the return url.  We'll have to confirm the payment
		#from paypal via IPN anyways, but the following purchase method will
		#just set the status of bounty to pending payment
		get 'purchase' => 'bounties/bounties#purchase'

		#IPN url
		post 'ipn_notification' => 'bounties/bounties#ipn_notification'

		post  'payment_request' => 'bounties/bounties#payment_request', as: 'payment_request'

		post 'claim' => 'bounties/bounties#claim'
	end


	resources :bounties, path: 'my-posted-bounties', controller: 'bounties/posted_bounties', as: 'posted_bounties' do
		get 'cancel' => 'bounties/posted_bounties#cancel', as: 'cancel'
		patch 'rate' => 'bounties/posted_bounties#rate', as: 'rate'
		patch 'claim' => 'bounties/posted_bounties#claim', as: 'claim'
		patch 'deny' => 'bounties/posted_bounties#deny', as: 'deny'
	end
	resources :bounties, path: 'my-claimed-bounties', controller: 'bounties/claimed_bounties', as: 'claimed_bounties' do
		get 'cancel' => 'bounties/claimed_bounties#cancel', as: 'cancel'
		patch 'rate' => 'bounties/claimed_bounties#rate', as: 'rate'
	end

	resources :profiles do
		get 'blocks-and-feedback' => 'profiles#blocks_and_feedback'
		get 'favorites' => 'profiles#favorites'
		get 'feedback' => 'profiles#feedback'
		get 'contracts' => 'profiles#contracts'
    resource :donation, only: [:new, :create, :index ]
    resources :ratings, shallow: true, except: [ :destroy ]
	end

	resources :donations, only: []  do
		post 'ipn_notification' => 'donations#ipn_notification', on: :member
		get  'thanks' => 'donations#thanks', on: :member
	end

	resources :charities do
		get 'charities' => 'charities#index'
	end

	get 'messages/trash' => 'messages#trash', as: "trash_messages"
	resources :messages do

	end
	get 'notifications' => 'messages#notifications'

	get 'invite_user' => 'rosters#invite_user'

	get 'dashboard' => 'dashboard#index', as: 'dashboard'

	get 'games' => 'games#index', as: 'games'
	get 'about' => 'pages#about', as: 'about'
	get 'leaderboard' => 'pages#leaderboard', as: 'leaderboard'
	get 'tos' => 'pages#tos', as: 'tos'
	get 'privacy' => 'pages#privacy', as: 'privacy'
	get 'thankyou' => 'pages#thankyou', as: 'thankyou'
	get 'faq' => 'pages#faq', as: 'faq'
	get 'how_to' => 'pages#how_to', as: 'how_to'
	get 'policies' => 'pages#policies', as: 'policies'
	get 'PUR' => 'pages#gamestop', as: 'gamestop'
	get 'google0dad1a6d425ae80a.html' => 'pages#google_verification'
	post 'default-ipn-notification' => 'pages#default_ipn_notification'
	get 'destiny-lfg' => 'pages#destiny_landing'
	get 'updates' => 'pages#updates', as: 'updates'

app/controllers/admin/events_controller.rb
class Admin::EventsController < InheritedResources::Base
	before_filter :authenticate_admin!
	respond_to :html
  defaults :resource_class => Contract

  def index
    @events = initialize_grid(Contract,
      order: 'created_at',
      order_direction: 'desc',
      per_page: 30,
      name: 'events',
			enable_export_to_csv: true,
			csv_file_name: 'events',
    )
		export_grid_if_requested
  end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < EventsController
  respond_to :json
  protect_from_forgery with: :null_session
  skip_before_filter :authenticate_user!
  skip_before_filter :set_upcoming_events
  acts_as_token_authentication_handler_for User

  # Get the list of upcoming events that a user has created or has been invited to
  #
  # GET /api/v1/my-events
  #
  # @return [Array<Contract>] events
  def index
    set_upcoming_events
    respond_with @upcoming_events, each_serializer: Api::V1::CompactContractSerializer, :current_user => current_user
  end

end

app/controllers/events_controller.rb
# coding: utf-8
class EventsController < InheritedResources::Base
  include SortsAndFilters
  defaults :resource_class => Contract
  before_filter :authenticate_user! 
  before_filter :get_collection, only: [:index]
  before_filter :filter_params, only: [:index]
  before_filter  :set_search, only: [:index]

  respond_to :html, :js

  def index
    @invited_rosters = current_user.invites.where('status' => 0).map{|r| [r.contract_id]}
    @invites = Roster.where('id' => @invited_rosters).where('start_date_time > now()').order("start_date_time ASC")


    @resource.order(start_date_time: :asc)
    @recent_events = @resource.page(params[:page])

  end

  def view_all
    # Set default params for the grid to show more relevant data
    # ACtually, don't
    # params[:utf8] ||= '✓'
    # params[:grid] ||= {}
    # params[:grid][:f] ||= {}
    # params[:grid][:f][:status] ||= ["Claimed", "Complete", "Invoiced", "Open", "Payment Complete"]

    @all = initialize_grid(current_user.all_contracts,
      order: 'start_date_time',
      order_direction: 'desc',
      per_page: 120,
      name: 'grid',
        # Wice Grid support only DB ordering, create a custom filter to order contract types
        # internally known as Contract, Bounty, and Roster which map to 'LFP' and 'GR'
      custom_order: {
        'contracts.contract_type' => "CASE contracts.contract_type WHEN 'Roster' THEN 'GR' ELSE 'LFP' END"
      }
    )

  end

  def show
    event = resource
      # This will include social sharing crawl of meta
      if current_user.nil?
        if resource.contract_type == "Roster"
          @public_event = 'roster'
          @event = Roster.find(resource.id)
          @roster_users = @event.confirmed_users
              @waitlist_users = @event.waitlist_users
              render file: "app/views/events/public_roster.html.erb"
          elsif resource.contract_type == "Contract" || event.contract_type == "Bounty"
            @public_event = 'availability'
          @event = Contract.find(resource.id)
            render file: "app/views/events/public_availability.html.erb"
          end
      else
        if resource.contract_type == "Roster"
          redirect_to(roster_path resource.id)
        elsif resource.contract_type == "Contract" || event.contract_type == "Bounty"
          if resource.buyer_id != nil && current_user.id == resource.buyer_id
            redirect_to(claimed_contract_path resource.id)
          elsif resource.seller_id != nil && current_user.id == resource.seller_id
            redirect_to(posted_contract_path resource.id)
          else
            @event = Contract.find(resource.id)
            render file: "app/views/events/public_availability.html.erb"
          end
        else
          redirect_to(new_user_session_path)
        end
      end

  end

  protected

  def get_collection
    # @upcoming_events = current_user.active_contracts.where('start_date_time > now()')
    @resource = current_user.all_contracts.where(["'status' != ? AND 'status' != ? AND 'status' != ?", 'Closed', 'Expired', 'Cancelled'])

  end

end

app/views/admin/events/_events_grid.html.erb
<%= define_grid(@events, show_filters: :yes, hide_csv_button: true, html: {class: 'table table-responsive admin-games table-striped data-tr'}) do |g|

	g.column name: 'Host', in_csv: false do | e |
		link_to admin_user_path(e.owner) do
			raw "<h5> #{e.owner.username} </h5>"
		end
	end
	g.column name: 'Host', in_html: false do | e |
		e.owner.username
	end

  g.column name: 'Host Email' do | e |
    e.owner.email
  end

	g.column name: 'Event #', attribute: 'id'

	g.column name: 'Type', attribute: 'contract_type', detach_with_id: :type_filter do | e |
		e.contract_type
	end

  g.column name: 'Visibility', attribute: 'private', detach_with_id: :visibility_filter, custom_filter: {'Private' => 1, 'Public' => 0} do | e |
    e.private? ? 'Private' : 'Public'
  end

  g.column name: 'Starts At', attribute: 'start_date_time', detach_with_id: :start_date_filter do | e |
    e.start_date_time.strftime("%Y/%m/%d %I:%M%p")
  end

  g.column name: 'Roster Size' do | e |
    if e.roster?
      r = Roster.find e.id
      "#{r.confirmed_users_count} / #{r.max_roster_size}"
    else
      num = (e.buyer.present? ? 1 : 0) + (e.seller.present? ? 1 : 0)
      "#{num} / 2"
    end
  end

  g.column name: 'Cancellation Date', attribute: 'cancelled_at' do | e |
      e.cancelled_at.strftime("%Y/%m/%d %I:%M%p") if e.cancelled_at.present?
  end

  g.column name: 'Created At', attribute: 'created_at', detach_with_id: :created_at_filter do | e |
    e.created_at.strftime("%Y/%m/%d %I:%M%p")
  end
end -%>

app/views/admin/events/_grid_form.html.erb
<%= form_tag admin_events_path, method: 'get', html: {role: "form"}, class: "wice_grid_form" do %>
  <div class="row">
    <div class="col-md-6">
  		<div class="form-group">
  			<label>Type</label>
  			<%= grid_filter @events, :type_filter %>
  		</div>
    </div>
    <div class="col-md-6">
  		<div class="form-group">
  			<label>Private?</label>
  			<%= grid_filter @events, :visibility_filter %>
  		</div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
  		<div class="form-group">
  			<label>Starts At</label>
  			<%= grid_filter @events, :start_date_filter %>
  		</div>
    </div>
    <div class="col-md-6">
  		<div class="form-group">
  			<label>Created At</label>
  			<%= grid_filter @events, :created_at_filter %>
  		</div>
    </div>
	</div>
  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <label>&nbsp;</label>
        <button type="submit" class="btn btn-primary btn-sm btn-block">Search</button>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/events/index.html.erb
<%= render partial: 'events_grid' %>
<div class="background-block content-area">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<%= render "layouts/adminnav" %>
			</div>
			<div class="col-md-9">
				<%= render 'layouts/flash' %>
      	<h2 class="mt0">View Events <span class="pull-right"><a class="btn btn-primary" id="export_csv" data-grid-name="events" href="events?events%5Bexport%5D=csv">Export To CSV</a></span></h2>
        <script type="text/javascript">
          $(function() {
            var $a = $('#export_csv');
            $a.click(function(e) {
              e.preventDefault();
              var url = location.href;
              if (url.indexOf('?') === -1) url += '?'
              url += '&events%5Bexport%5D=csv';
              location.href = url;
            });
          });
        </script>
				<p id="notice"><%= notice %></p>
				<div class="table-responsive">
		      <%= render "grid_form" %>
					<%= render_grid(@events) %>
				</div>
			</div>
		</div>
	</div>
</div>