config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

	scope module: 'clans' do
	  resources :clans do
	    resources :clan_messages, shallow: true
			resources :clan_members, shallow: true
			resources :clan_messages, shallow: true
			resources :clan_ranks, shallow: true
			resources :clan_events, only: [:index]
			resources :clan_links, only: [:index]
			resources :clan_contacts, only: [:create]
			resources :clan_applications, only: [:index, :destroy, :create, :show] do
				patch 'accept' => 'clan_applications#accept', as: :accept, on: :member
			end
			resources :clan_donations, only: [:create] do
				post 'ipn_notification' => 'clan_donations#ipn_notification', on: :member
				get  'thanks' => 'clan_donations#thanks', on: :member
			end
			patch 'change_owner' => 'clans#change_owner', on: :member
			patch 'unblock_member/:clan_member_id' => 'clans#unblock_member', on: :member
			patch 'clan_members/:clan_member_id' => 'clans#clan_members_update', on: :member
			delete 'remove_member/:clan_member_id' => 'clans#remove_member', on: :member
	  end
	  resources :clan_invites
	  post 'clan_invites/:clan_invite_id/accept' => 'clan_invites#accept', as: 'accept_clan_invite'
	end

  get 'clan_notices/:clan_id/new' => 'clans/clan_notices#new', as: 'new_clan_notice'
  get 'clan_notices/:id' => 'clans/clan_notices#show', as: 'clan_notice'
  post 'clan_notices/:clan_id/new' => 'clans/clan_notices#create'
  delete 'clan_notices/:id' => 'clans/clan_notices#destroy', as: 'delete_clan_notice'

  get 'system_notices/new' => 'system_notices#new', as: 'new_system_notice'
  get 'system_notices/:id' => 'system_notices#show', as: 'system_notice'
  get 'system_notices' => 'system_notices#index', as: 'system_notices'
  post 'system_notices/new' => 'system_notices#create'
  delete 'system_notices/:id' => 'system_notices#destroy', as: 'delete_system_notice'

	resources :announcements, only: :index
	post 'announcements/read' => 'announcements#read'

	devise_for :admins, controllers: { sessions: 'admin/sessions' }
	devise_for :users,  controllers: { sessions: 'user/sessions', registrations: 'user/registrations', confirmations: 'user/confirmations' }

	authenticate :admin do
		mount Sidekiq::Web => '/sidekiq'
  end

	authenticated :admin do
		root to: 'admin/dashboard#index', as: :authenticated_admin
		namespace :admin do
			resources :games
			resources :game_systems
			resources :charities
			resources :cancellations
		  resources :users
			resources :rosters
			resources :reports
			resources :events, only: :index
			get 'cancellations/(:rosters)' => 'cancellations#index'
			patch 'cancellations/:id/uncancel' => 'cancellations#uncancel'
			post 'users/:id/become/(:prev_action)' => 'users#become', as: 'user_become'
			get 'users/:id/confirm' => 'users#confirm', as: 'user_confirm'
			get 'users/:id/account'  => 'users#account', as: 'user_account'
		end
	end

	authenticated :user do
		root to: 'dashboard#index', as: :authenticated_user
	end

	unauthenticated do
		devise_scope :user do
			root to: 'pages#home', as: :unauthenticated_user
			get 'tosmodal' => 'user/registrations#tosmodal', as: 'tosmodal'
		end
	end

	#the following resources are actually all the same model - the user.
	#it just made breaking up the CRUD for the user easier because we're using
	#inherited resources.
	resource :user, path: 'profile', controller: 'profile/profile', as: 'profile'
	namespace :profile do
		resource :user, path: 'country', controller: 'country', as: 'country', only: [ :edit, :update ]
		resource :user, path: 'account', controller: 'account', as: 'account'
		resource :user, path: 'games', controller: 'games_and_systems', as: 'games_and_systems'
		resources :blocks
		resources :favorites
                resource :notifications, only: [:edit, :update]
		get 'avatar' => 'avatar#index'
		get 'subscription' => 'subscription#index'
                post 'add-game-modal' => 'games_and_systems#add_game', as: 'add_game'
                get 'check-user-system' => 'games_and_systems#check_game', as: 'check_game'
	end

	#the following both deal with the contracts controller - my-contracts is
	#obviously just scoped to the current user.
	get 'contracts/close_pay_pal' => 'contracts/contracts#close_pay_pal'

	resources :contracts, controller: 'contracts/contracts', path: 'looking-for-players'

	resources :contracts, controller: 'players/players', path: 'players', as: 'players'

	resources :contracts, controller: 'contracts/contracts', only: [] do
		#we're going to break the REST model as paypal doesn't allow sending
		#post/patch method via the return url.  We'll have to confirm the payment
		#from paypal via IPN anyways, but the following purchase method will
		#just set the status of contract to pending payment
		get 'purchase' => 'contracts/contracts#purchase'

		#IPN url
		post 'ipn_notification' => 'contracts/contracts#ipn_notification'

		post  'payment_request' => 'contracts/contracts#payment_request', as: 'payment_request'

		post 'claim' => 'contracts/contracts#claim'

	end

	namespace :subscriptions do
		get 'abort'
		get 'cancel'
		get 'ipn_notification'
	end

	resources :subscription_plans, only: [] do
    	resources :subscriptions, shallow: true
  	end

	get 'multiple_times' => 'contracts/posted_contracts#multiple_times_new', as: 'multiple_times_new'
	post 'multiple_times' => 'contracts/posted_contracts#multiple_times_create', as: 'multiple_times_create'

	resources :contracts, path: 'my-posted-events', controller: 'contracts/posted_contracts', as: 'posted_contracts' do
		get 'cancel' => 'contracts/posted_contracts#cancel', as: 'cancel'
		patch 'rate' => 'contracts/posted_contracts#rate', as: 'rate'
		patch 'claim' => 'contracts/posted_contracts#claim', as: 'claim'
		patch 'deny' => 'contracts/posted_contracts#deny', as: 'deny'
	end

	resources :contracts, path: 'my-claimed-events', controller: 'contracts/claimed_contracts', as: 'claimed_contracts' do
		get 'cancel' => 'contracts/claimed_contracts#cancel', as: 'cancel'
		patch 'rate' => 'contracts/claimed_contracts#rate', as: 'rate'
	end

	resources :rosters do
		get 'cancel', as: 'cancel', on: :member
		get 'add_invitees' => 'rosters#add_invitees', on: :member
    	resources :roster_messages, shallow: true
    	resources :invites, only: [ :create ]
	end

	resources :roster_invites, only: [:create]

	resources :invites, only: [:destroy] do
		patch 'claim', on: :member
		patch 'decline', on: :member
		patch 'waitlist', on: :member
		patch 'no_show', on: :member
		patch 'reconfirm', on: :member
		put  :update_position, on: :member
	end

	resources :events, path: 'my-events', only: :index
	resource :events do
		get 'view_all' => 'events#view_all'
	end
	resources :events, only: :show

	get 'add_invitees' => 'rosters#add_invitees', as: 'add_invitees'
	post 'add_invitees_create' => 'invites#add_invitees_create', as: 'add_invitees_create'

	get 'add_game_modal' => 'dashboard#add_game_modal'

	#the following both deal with the bounties controller - my-bounties is
	#obviously just scoped to the current user.
	get 'bounties/close_pay_pal' => 'bounties/bounties#close_pay_pal'
	get 'bounties/feed' => 'bounties/bounties#feed'

	resources :bounties, controller: 'bounties/bounties', path: 'public-games'

	resources :bounties, controller: 'bounties/bounties', only: []  do
		#we're going to break the REST model as paypal doesn't allow sending
		#post/patch method via the return url.  We'll have to confirm the payment
		#from paypal via IPN anyways, but the following purchase method will
		#just set the status of bounty to pending payment
		get 'purchase' => 'bounties/bounties#purchase'

		#IPN url
		post 'ipn_notification' => 'bounties/bounties#ipn_notification'

		post  'payment_request' => 'bounties/bounties#payment_request', as: 'payment_request'

		post 'claim' => 'bounties/bounties#claim'
	end


	resources :bounties, path: 'my-posted-bounties', controller: 'bounties/posted_bounties', as: 'posted_bounties' do
		get 'cancel' => 'bounties/posted_bounties#cancel', as: 'cancel'
		patch 'rate' => 'bounties/posted_bounties#rate', as: 'rate'
		patch 'claim' => 'bounties/posted_bounties#claim', as: 'claim'
		patch 'deny' => 'bounties/posted_bounties#deny', as: 'deny'
	end
	resources :bounties, path: 'my-claimed-bounties', controller: 'bounties/claimed_bounties', as: 'claimed_bounties' do
		get 'cancel' => 'bounties/claimed_bounties#cancel', as: 'cancel'
		patch 'rate' => 'bounties/claimed_bounties#rate', as: 'rate'
	end

	resources :profiles do
		get 'blocks-and-feedback' => 'profiles#blocks_and_feedback'
		get 'favorites' => 'profiles#favorites'
		get 'feedback' => 'profiles#feedback'
		get 'contracts' => 'profiles#contracts'
    resource :donation, only: [:new, :create, :index ]
    resources :ratings, shallow: true, except: [ :destroy ]
	end

	resources :donations, only: []  do
		post 'ipn_notification' => 'donations#ipn_notification', on: :member
		get  'thanks' => 'donations#thanks', on: :member
	end

	resources :charities do
		get 'charities' => 'charities#index'
	end

	get 'messages/trash' => 'messages#trash', as: "trash_messages"
	resources :messages do

	end
	get 'notifications' => 'messages#notifications'

	get 'invite_user' => 'rosters#invite_user'

	get 'dashboard' => 'dashboard#index', as: 'dashboard'

	get 'games' => 'games#index', as: 'games'
	get 'about' => 'pages#about', as: 'about'
	get 'leaderboard' => 'pages#leaderboard', as: 'leaderboard'
	get 'tos' => 'pages#tos', as: 'tos'
	get 'privacy' => 'pages#privacy', as: 'privacy'
	get 'thankyou' => 'pages#thankyou', as: 'thankyou'
	get 'faq' => 'pages#faq', as: 'faq'
	get 'how_to' => 'pages#how_to', as: 'how_to'
	get 'policies' => 'pages#policies', as: 'policies'
	get 'PUR' => 'pages#gamestop', as: 'gamestop'
	get 'google0dad1a6d425ae80a.html' => 'pages#google_verification'
	post 'default-ipn-notification' => 'pages#default_ipn_notification'
	get 'destiny-lfg' => 'pages#destiny_landing'
	get 'updates' => 'pages#updates', as: 'updates'

app/models/donation.rb
class Donation < ActiveRecord::Base

  MAX_CENTS = 200_00
  MIN_CENTS = 1_00

  has_many :logs, class_name: "DonationPaypalLog"

  include MoneyPenny

  dollarize :amount_cents

  belongs_to :user
  belongs_to :donatee, class_name: "User"

  validate :reasonable_amount

  enum status: [ :pending, :complete, :error, :unknown ]


  def reasonable_amount
    return errors.add(:amount_dollars, "must be at least a $%.2f" % [ 0.01 * MIN_CENTS ]) unless amount_cents and amount_cents >= MIN_CENTS
    errors.add(:amount_dollars, "please limit to $%.2f" % [ 0.01 * MAX_CENTS ]) unless amount_cents <= MAX_CENTS
  end
  
end

app/controllers/donations_controller.rb
class DonationsController < InheritedResources::Base


	before_filter :authenticate_user!, :except =>[:ipn_notification]
  before_filter :find_donatee, only: [ :new, :create ]
	protect_from_forgery :except => [:ipn_notifcation]

  def new
    @donation = build_resource
    @donation.donatee = @donatee
  end

  def create
    @donation = build_resource
    @donation.donatee = @donatee

    if @donation.save
		  @pay_response = build_payment_request(@donation)
      
      unless @pay_response.success?
        @donation.logs.create( log: @pay_response.error.first.message )
			  flash[:error] = 'There was a problem submitting your payment. Please have the recipient check their PayPal email address, and try again.'
			  return redirect_to request.referer
      end

      @donation.logs.create(log: @pay_response.to_json )
			redirect_to "#{Rails.application.config.adaptive_payments_url}#{@pay_response.payKey}"

    else
      render "new"
    end
  end

  def thanks
    @donation = current_user.donations.find(params[:id])
    redirect_to root_path, flash: { success: "Your donation has been sent to #{@donation.donatee.username}" }
  rescue 
    redirect_to root_path, flash: { error: "Sorry, we were not able to find that page." }
  end

  def ipn_notification
		if api.ipn_valid?(request.raw_post) and params[:id]
			@donation = Donation.find(params[:id])
			@donation.logs.create(log: params.to_json)

      if params[:status].eql?("COMPLETED")
        @donation.pay_pal_transaction_id = params[:transaction]["0"][".id"]
        @donation.complete!
      else
        # A response that we do not handle
        @donation.unknown!
      end
		end

		#we just need to return a blank 200 so IPN will stop posting back to us
		render :text => ""
	end

  private

    def donation_params
      params.require(:donation).permit(:amount_dollars)
    end

    def find_donatee
      @donatee = User.find_by_username( params[:profile_id] )
    end

    def begin_of_association_chain
      @current_user
    end

		def api
			@api ||= PayPal::SDK::AdaptivePayments::API.new
		end

    def build_payment_request(donation)
      donatee = donation.donatee
      @pay = api.build_pay({
        :actionType => "PAY",
        :cancelUrl => "#{Rails.application.config.return_host}/profiles/#{donatee.username}",
        :currencyCode => "USD",
        :feesPayer => "EACHRECEIVER",
        :ipnNotificationUrl => "#{Rails.application.config.ipn_host}#{ipn_notification_donation_path(donation)}",
        :receiverList => {
          :receiver => [{
            #merc
            :amount => donation.amount_dollars.to_f,
            :email =>  donatee.paypal_email.present?  ? donatee.paypal_email : donatee.email
          }]
        },
        :returnUrl => "#{Rails.application.config.return_host}#{thanks_donation_path(donation)}" 
      })

      donation.logs.create( log: @pay.to_json )
      return @api.pay(@pay)
    end
	end

app/views/donations/_form.html.erb
<%= form_for(@donation, url: profile_donation_path( @donatee.username )  ) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label>Donation Amount</label>
        <%= f.number_field :amount_dollars, class: 'form-control', placeholder: 'in dollars', step: '.25', value: @donation.amount_dollars %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary', value: 'Submit' %>
  </div>
<% end %>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Donations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Donatee</th>
      <th>Amount cents</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.user %></td>
        <td><%= donation.donatee %></td>
        <td><%= donation.amount_cents %></td>
        <td><%= donation.state %></td>
        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<div class="background-block content-area">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<div class="account-nav profile-nav">
					<div class="side-nav-avatar image-container">
						<%= link_to profiles_path + '/' + @donatee.try(:username) do %>
							<%= image_tag(@donatee.avatar_url) %>
						<% end %>
					</div>

					<div class="side-nav-container container-box">
						<div class="form-group">
							<label>Personality Rating</label>
							<%if @donatee.personality_rating == 0 %>
								N/A
							<% else %>
								<span class="psa-rating-read-only" data-score="<%= @donatee.personality_rating %>">

								</span>
							<% end %>
						</div>
						<div class="form-group">
							<label>Skill Rating</label>
							<%if @donatee.skill_rating == 0 %>
								N/A
							<% else %>
								<span class="psa-rating-read-only" data-score="<%= @donatee.skill_rating %>">

								</span>
							<% end %>
						</div>
						<div class="form-group">
							<label>Approval Rating</label>
							<%if @donatee.approval_rating == 0%>
								N/A
							<% else %>
								<span class="psa-rating-read-only" data-score="<%= @donatee.approval_rating %>">

								</span>
							<% end %>
						</div>
						<div class="form-group">
							<label>Generosity Rating</label>
							<%if @donatee.generosity_rating == 0%>
								N/A
							<% else %>
								<span class="psa-rating-read-only" data-score="<%= @donatee.generosity_rating %>">

								</span>
							<% end %>
						</div>
						<%= link_to "View All Feedback", profiles_path + '/' + @donatee.username + '/feedback'  %>
					</div>

					<div class="side-nav-container container-box">
						<div class="form-group">
							<label>Experience</label>
							<p><%= @donatee.contracts_completed %></p>
						</div>
						<div class="form-group">
							<label>Cancellation Rate</label>
							<p> <%= @donatee.cancellation_rate.present? ? "#{@donatee.cancellation_rate}%" : 'N/A' %>  </p>
						</div>
					</div>

					<div class="side-nav-container container-box">
						<div class="form-group">
							<label>Player is a Minor</label>
							<p><%= @donatee.date_of_birth <= (Time.now - 18.years) ? 'No' : 'Yes' %></p>
						</div>
						<% if @donatee.will_play.present? %>
							<div class="form-group">
								<label>Will Play</label>
								<%= @donatee.will_play %>
							</div>
						<% end %>
						<% if @donatee.newbie_patience_level.present? %>
							<div class="form-group">
								<label>Newb Patience Level</label>
								<%= @donatee.newbie_patience_level %>
							</div>
						<% end %>
						<% if @donatee.playing_games_since.present? %>
							<div class="form-group">
								<label>Playing Games Since</label>
								<%= @donatee.playing_games_since %>
							</div>
						<% end %>
						<div class="form-group">
							<label>Languages</label>
							<%= @donatee.languages.join(', ') %>
						</div>
						<% if @donatee.may_record_or_stream.present? %>
							<div class="form-group">
								<label>May Record or Stream</label>
								<%= @donatee.may_record_or_stream %>
							</div>
						<% end %>
					</div>
				</div>
			</div>

	  		<div class="col-md-9">
				<h1 class="mt0">Donate to <%= @donatee.username %></h1>

				<%= render 'form' %>
				<br>
				<p>
					<%= link_to 'Back to Profile', profiles_path + '/' + @donatee.try(:username) %>
				</p>
			</div>
		</div>
	</div>
</div>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @donation.user %>
</p>

<p>
  <strong>Donatee:</strong>
  <%= @donation.donatee %>
</p>

<p>
  <strong>Amount cents:</strong>
  <%= @donation.amount_cents %>
</p>

<p>
  <strong>State:</strong>
  <%= @donation.state %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>