config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

	scope module: 'clans' do
	  resources :clans do
	    resources :clan_messages, shallow: true
			resources :clan_members, shallow: true
			resources :clan_messages, shallow: true
			resources :clan_ranks, shallow: true
			resources :clan_events, only: [:index]
			resources :clan_links, only: [:index]
			resources :clan_contacts, only: [:create]
			resources :clan_applications, only: [:index, :destroy, :create, :show] do
				patch 'accept' => 'clan_applications#accept', as: :accept, on: :member
			end
			resources :clan_donations, only: [:create] do
				post 'ipn_notification' => 'clan_donations#ipn_notification', on: :member
				get  'thanks' => 'clan_donations#thanks', on: :member
			end
			patch 'change_owner' => 'clans#change_owner', on: :member
			patch 'unblock_member/:clan_member_id' => 'clans#unblock_member', on: :member
			patch 'clan_members/:clan_member_id' => 'clans#clan_members_update', on: :member
			delete 'remove_member/:clan_member_id' => 'clans#remove_member', on: :member
	  end
	  resources :clan_invites
	  post 'clan_invites/:clan_invite_id/accept' => 'clan_invites#accept', as: 'accept_clan_invite'
	end

  get 'clan_notices/:clan_id/new' => 'clans/clan_notices#new', as: 'new_clan_notice'
  get 'clan_notices/:id' => 'clans/clan_notices#show', as: 'clan_notice'
  post 'clan_notices/:clan_id/new' => 'clans/clan_notices#create'
  delete 'clan_notices/:id' => 'clans/clan_notices#destroy', as: 'delete_clan_notice'

  get 'system_notices/new' => 'system_notices#new', as: 'new_system_notice'
  get 'system_notices/:id' => 'system_notices#show', as: 'system_notice'
  get 'system_notices' => 'system_notices#index', as: 'system_notices'
  post 'system_notices/new' => 'system_notices#create'
  delete 'system_notices/:id' => 'system_notices#destroy', as: 'delete_system_notice'

	resources :announcements, only: :index
	post 'announcements/read' => 'announcements#read'

	devise_for :admins, controllers: { sessions: 'admin/sessions' }
	devise_for :users,  controllers: { sessions: 'user/sessions', registrations: 'user/registrations', confirmations: 'user/confirmations' }

	authenticate :admin do
		mount Sidekiq::Web => '/sidekiq'
  end

	authenticated :admin do
		root to: 'admin/dashboard#index', as: :authenticated_admin
		namespace :admin do
			resources :games
			resources :game_systems
			resources :charities
			resources :cancellations
		  resources :users
			resources :rosters
			resources :reports
			resources :events, only: :index
			get 'cancellations/(:rosters)' => 'cancellations#index'
			patch 'cancellations/:id/uncancel' => 'cancellations#uncancel'
			post 'users/:id/become/(:prev_action)' => 'users#become', as: 'user_become'
			get 'users/:id/confirm' => 'users#confirm', as: 'user_confirm'
			get 'users/:id/account'  => 'users#account', as: 'user_account'
		end
	end

	authenticated :user do
		root to: 'dashboard#index', as: :authenticated_user
	end

	unauthenticated do
		devise_scope :user do
			root to: 'pages#home', as: :unauthenticated_user
			get 'tosmodal' => 'user/registrations#tosmodal', as: 'tosmodal'
		end
	end

	#the following resources are actually all the same model - the user.
	#it just made breaking up the CRUD for the user easier because we're using
	#inherited resources.
	resource :user, path: 'profile', controller: 'profile/profile', as: 'profile'
	namespace :profile do
		resource :user, path: 'country', controller: 'country', as: 'country', only: [ :edit, :update ]
		resource :user, path: 'account', controller: 'account', as: 'account'
		resource :user, path: 'games', controller: 'games_and_systems', as: 'games_and_systems'
		resources :blocks
		resources :favorites
                resource :notifications, only: [:edit, :update]
		get 'avatar' => 'avatar#index'
		get 'subscription' => 'subscription#index'
                post 'add-game-modal' => 'games_and_systems#add_game', as: 'add_game'
                get 'check-user-system' => 'games_and_systems#check_game', as: 'check_game'
	end

	#the following both deal with the contracts controller - my-contracts is
	#obviously just scoped to the current user.
	get 'contracts/close_pay_pal' => 'contracts/contracts#close_pay_pal'

	resources :contracts, controller: 'contracts/contracts', path: 'looking-for-players'

	resources :contracts, controller: 'players/players', path: 'players', as: 'players'

	resources :contracts, controller: 'contracts/contracts', only: [] do
		#we're going to break the REST model as paypal doesn't allow sending
		#post/patch method via the return url.  We'll have to confirm the payment
		#from paypal via IPN anyways, but the following purchase method will
		#just set the status of contract to pending payment
		get 'purchase' => 'contracts/contracts#purchase'

		#IPN url
		post 'ipn_notification' => 'contracts/contracts#ipn_notification'

		post  'payment_request' => 'contracts/contracts#payment_request', as: 'payment_request'

		post 'claim' => 'contracts/contracts#claim'

	end

	namespace :subscriptions do
		get 'abort'
		get 'cancel'
		get 'ipn_notification'
	end

	resources :subscription_plans, only: [] do
    	resources :subscriptions, shallow: true
  	end

	get 'multiple_times' => 'contracts/posted_contracts#multiple_times_new', as: 'multiple_times_new'
	post 'multiple_times' => 'contracts/posted_contracts#multiple_times_create', as: 'multiple_times_create'

	resources :contracts, path: 'my-posted-events', controller: 'contracts/posted_contracts', as: 'posted_contracts' do
		get 'cancel' => 'contracts/posted_contracts#cancel', as: 'cancel'
		patch 'rate' => 'contracts/posted_contracts#rate', as: 'rate'
		patch 'claim' => 'contracts/posted_contracts#claim', as: 'claim'
		patch 'deny' => 'contracts/posted_contracts#deny', as: 'deny'
	end

	resources :contracts, path: 'my-claimed-events', controller: 'contracts/claimed_contracts', as: 'claimed_contracts' do
		get 'cancel' => 'contracts/claimed_contracts#cancel', as: 'cancel'
		patch 'rate' => 'contracts/claimed_contracts#rate', as: 'rate'
	end

	resources :rosters do
		get 'cancel', as: 'cancel', on: :member
		get 'add_invitees' => 'rosters#add_invitees', on: :member
    	resources :roster_messages, shallow: true
    	resources :invites, only: [ :create ]
	end

	resources :roster_invites, only: [:create]

	resources :invites, only: [:destroy] do
		patch 'claim', on: :member
		patch 'decline', on: :member
		patch 'waitlist', on: :member
		patch 'no_show', on: :member
		patch 'reconfirm', on: :member
		put  :update_position, on: :member
	end

	resources :events, path: 'my-events', only: :index
	resource :events do
		get 'view_all' => 'events#view_all'
	end
	resources :events, only: :show

	get 'add_invitees' => 'rosters#add_invitees', as: 'add_invitees'
	post 'add_invitees_create' => 'invites#add_invitees_create', as: 'add_invitees_create'

	get 'add_game_modal' => 'dashboard#add_game_modal'

	#the following both deal with the bounties controller - my-bounties is
	#obviously just scoped to the current user.
	get 'bounties/close_pay_pal' => 'bounties/bounties#close_pay_pal'
	get 'bounties/feed' => 'bounties/bounties#feed'

	resources :bounties, controller: 'bounties/bounties', path: 'public-games'

	resources :bounties, controller: 'bounties/bounties', only: []  do
		#we're going to break the REST model as paypal doesn't allow sending
		#post/patch method via the return url.  We'll have to confirm the payment
		#from paypal via IPN anyways, but the following purchase method will
		#just set the status of bounty to pending payment
		get 'purchase' => 'bounties/bounties#purchase'

		#IPN url
		post 'ipn_notification' => 'bounties/bounties#ipn_notification'

		post  'payment_request' => 'bounties/bounties#payment_request', as: 'payment_request'

		post 'claim' => 'bounties/bounties#claim'
	end


	resources :bounties, path: 'my-posted-bounties', controller: 'bounties/posted_bounties', as: 'posted_bounties' do
		get 'cancel' => 'bounties/posted_bounties#cancel', as: 'cancel'
		patch 'rate' => 'bounties/posted_bounties#rate', as: 'rate'
		patch 'claim' => 'bounties/posted_bounties#claim', as: 'claim'
		patch 'deny' => 'bounties/posted_bounties#deny', as: 'deny'
	end
	resources :bounties, path: 'my-claimed-bounties', controller: 'bounties/claimed_bounties', as: 'claimed_bounties' do
		get 'cancel' => 'bounties/claimed_bounties#cancel', as: 'cancel'
		patch 'rate' => 'bounties/claimed_bounties#rate', as: 'rate'
	end

	resources :profiles do
		get 'blocks-and-feedback' => 'profiles#blocks_and_feedback'
		get 'favorites' => 'profiles#favorites'
		get 'feedback' => 'profiles#feedback'
		get 'contracts' => 'profiles#contracts'
    resource :donation, only: [:new, :create, :index ]
    resources :ratings, shallow: true, except: [ :destroy ]
	end

	resources :donations, only: []  do
		post 'ipn_notification' => 'donations#ipn_notification', on: :member
		get  'thanks' => 'donations#thanks', on: :member
	end

	resources :charities do
		get 'charities' => 'charities#index'
	end

	get 'messages/trash' => 'messages#trash', as: "trash_messages"
	resources :messages do

	end
	get 'notifications' => 'messages#notifications'

	get 'invite_user' => 'rosters#invite_user'

	get 'dashboard' => 'dashboard#index', as: 'dashboard'

	get 'games' => 'games#index', as: 'games'
	get 'about' => 'pages#about', as: 'about'
	get 'leaderboard' => 'pages#leaderboard', as: 'leaderboard'
	get 'tos' => 'pages#tos', as: 'tos'
	get 'privacy' => 'pages#privacy', as: 'privacy'
	get 'thankyou' => 'pages#thankyou', as: 'thankyou'
	get 'faq' => 'pages#faq', as: 'faq'
	get 'how_to' => 'pages#how_to', as: 'how_to'
	get 'policies' => 'pages#policies', as: 'policies'
	get 'PUR' => 'pages#gamestop', as: 'gamestop'
	get 'google0dad1a6d425ae80a.html' => 'pages#google_verification'
	post 'default-ipn-notification' => 'pages#default_ipn_notification'
	get 'destiny-lfg' => 'pages#destiny_landing'
	get 'updates' => 'pages#updates', as: 'updates'

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  belongs_to :admin
  belongs_to :reportable, polymorphic: true

  validates_presence_of :reportable

  scope :created_by_user, -> (user) { where(:user => user) }
  # Gives a human-readable name for the reportable type
  #
  # @return [String] the name of the reportable type
  def reportable_type_name
    case reportable
    when User
      'User'
    when Roster
      'Roster'
    when Bounty
      'Bounty'
    when Contract
      'Contract'
    else
      r.reportable_type
    end
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < InheritedResources::Base
	before_filter :authenticate_admin!
	respond_to :html

  def index
    @reports = initialize_grid(collection,
      order: 'created_at',
      order_direction: 'desc',
      per_page: 30,
      name: 'grid',
    )
    super
  end

  def update
    resource.admin = current_admin
    resource.handled_at = DateTime.now
    super
  end

  private
    def permitted_params
      params.permit(report: [:admin_comment])
    end
end

app/controllers/api/v1/reports_controller.rb
class Api::V1::ReportsController < Api::BaseController
  respond_to :json
  protect_from_forgery with: :null_session
  acts_as_token_authentication_handler_for User

  # Creates a new report and assigns it to the current user as the reporter
  #
  # @param report [Report] required fields: `reportable_type`, `reportable_id`. Optional fields: `comment`
  #
  # @return [Boolean] `201` {success: true} if successful
  # @return [Array] `422` an array of errors keyed on the field name
  #
	def create
    # because a user is a valid reportable type, inherited resources apparently wants to
    # make the reportable be the current user rather than what the user passed in when you use build_resource.
    # to get around this, we just construct it manually
    resource = Report.new
    resource.reportable_type = params[:report][:reportable_type]
    resource.reportable_id = params[:report][:reportable_id]
    resource.comment = params[:report][:comment]

    if resource.valid?
      resource.user = current_user
      resource.save

      render json: {
        success: true
      }
    else
      render json: resource.errors, status: :unprocessable_entity
    end
	end

	protected
    def begin_of_association_chain
		current_user
    end

  	def permitted_params
  		params.permit(
  			report: [:reportable_type, :reportable_id, :comment]
  		)
    end
end

app/views/admin/reports/_reports_grid.html.erb
<%= define_grid(@reports, show_filters: false, hide_csv_button: true, html: {class: 'table table-responsive admin-users table-striped data-tr'}) do |g|
	g.column name: 'Type', attribute: 'reportable_type' do | r |
		link_to r.reportable_type_name, admin_report_path(r)
	end

	g.column name: 'Reported At', attribute: 'created_at' do | r |
		link_to long_date_time(r.created_at), admin_report_path(r)
	end

	g.column name: 'Handled At', attribute: 'handled_at' do | r |
		link_to long_date_time(r.handled_at), admin_report_path(r) if r.handled_at.present?
	end

	g.column name: 'Handled By', attribute: 'admin_id' do | r |
		link_to r.admin.email, admin_report_path(r) if r.admin.present?
	end

end -%>

app/views/admin/reports/_user_snippet.html.erb
<h3 class="mt0">User Info</h3>
<div class="container-box">
  <div class="form-group">
    <label>Username:</label>
    <%= link_to user.username, profiles_path() + "/#{user.username}" %>
  </div>
  <div class="form-group">
    <label>Email:</label>
    <%= user.email %>
  </div>
  <div class="form-group">
    <label>Sign In Count:</label>
    <%= user.sign_in_count %>
  </div>
</div>

app/views/admin/reports/index.html.erb
<%= render partial: 'reports_grid' %>
<div class="background-block content-area">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<%= render "layouts/adminnav" %>
			</div>
			<div class="col-md-9">
				<%= render 'layouts/flash' %>

      	<h2 class="mt0">Manage Reported Content</span></h2>

				<p id="notice"><%= notice %></p>
				<div class="table-responsive">
					<%= render_grid(@reports) %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/reports/show.html.erb
<div class="background-block content-area">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<%= render "layouts/adminnav" %>
			</div>
			<div class="col-md-9">
				<%= render 'layouts/flash' %>

      	<h2 class="mt0">Reported <%= resource.reportable_type_name %></span></h2>

				<p id="notice"><%= notice %></p>

        <div class="container-box">
          <%
          case resource.reportable
          when User
          %>
            <%= render 'user_snippet', user: resource.reportable %>
          <% when Roster %>
            <%= render '/rosters/roster_info', roster: resource.reportable, show_sharing: false %>
          <% when Bounty %>
            <%= render '/bounties/bounties/bounty_snippet', bounty: resource.reportable %>
          <% when Contract %>
            <h4>User: <%= resource.reportable.seller.username %></h4>
            <%= render '/contracts/posted_contracts/contract_snippet', contract: resource.reportable %>
          <% else %>
          <% end %>
        </div>

        <h3 class="mt0">Reported By</h3>
				<div class="container-box">
					<div class="form-group">
						<label>Username:</label>
						<%= resource.user.username %>
					</div>
					<div class="form-group">
						<label>Reports Sent:</label>
						<%= Report.created_by_user(resource.user).count %>
					</div>
          <div class="form-group">
            <label>Comment:</label>
            <%= resource.comment %>
          </div>
				</div>

        <h3 class="mt0">Admin Actions</h3>
        <div class="container-box">
          <%
          case resource.reportable
          when User
          %>
          <div class='row'>
            <div class ='col-md-3'><%= link_to "Edit User Account", admin_user_account_path(resource.reportable.id), class: "btn btn-primary" %></div>
            <div class = 'col-md-3'><%= link_to "Edit User Profile", admin_user_become_path(resource.reportable.id, prev_action: '/profile/edit'), method: :post,
              class: "btn btn-primary" %></div>
            <div class ='col-md-3'><%= button_to "Delete User Account", admin_user_path(resource.reportable.id), method: :delete, class: "btn btn-danger" %></div>
          </div>
          <% when Roster %>
            <%= link_to 'Edit Roster', admin_user_become_path(resource.reportable.buyer.id, prev_action: edit_roster_path(resource.reportable)), method: :post, class: "btn btn-primary" %>
          <% when Bounty %>
            <%= link_to 'Edit Bounty', admin_user_become_path(resource.reportable.buyer.id, prev_action: edit_bounty_path(resource.reportable)), method: :post, class: "btn btn-primary" %>
          <% when Contract %>
            <%= link_to 'Edit Availability', admin_user_become_path(resource.reportable.seller.id, prev_action: edit_posted_contract_path(resource.reportable)), method: :post, class: "btn btn-primary" %>
          <% else %>
          <% end %>
          <br />
          <% if resource.admin.present? %>
            <br />
            <div class="form-group">
              <label>Handled By:</label>
              <%= resource.admin.email %>
            </div>
            <div class="form-group">
              <label>Handled On:</label>
              <%= long_date_time(resource.handled_at) %>
            </div>
            <div class="form-group">
              <label>Comment:</label>
              <%= resource.admin_comment %>
            </div>
          <% else %>
            <%= bootstrap_form_for resource, :url => admin_report_path(resource) do | f | %>
              <%= f.text_area :admin_comment %>
              <%= f.submit value: 'Close Report', class: "btn btn-primary" %>
            <% end %>
          <% end %>
        </div>
        </div>

			</div>
		</div>
	</div>
</div>